In [1]:
import numpy as np
import gym
import torch

In [2]:
env = gym.make('HalfCheetah-v3')

In [8]:
obs_lst,t  = [], 0
obs = env.reset()
while t < 100000:
    obs_lst.append(obs)
    obs, _, done, _  = env.step(np.random.uniform(env.action_space.low, env.action_space.high))
    obs_lst.append(obs)
    if done:
        obs = env.reset()
    t+=1
    

In [4]:
np.mean(np.asarray(obs_lst), axis=0)

array([-0.1313595 ,  0.53531516,  0.007035  ,  0.01861835, -0.00180152,
        0.03665675, -0.02344995, -0.02015619, -0.07165087, -0.01473392,
       -0.00056798,  0.02806344, -0.05373638,  0.03396976,  0.00964424,
        0.03094805, -0.00594213])

In [9]:
np.mean(np.asarray(obs_lst), axis=0)

array([-0.16134366,  0.73647401,  0.00407596,  0.01796829, -0.00228325,
        0.03178342, -0.01983459, -0.0212972 , -0.0892334 , -0.01392782,
        0.01172412,  0.01951365, -0.05801415,  0.03212379,  0.0057655 ,
        0.03889271,  0.00887293])

In [12]:
x = np.eye(3)
y = np.ones(3)

In [15]:
(x - y)/y

array([[ 0., -1., -1.],
       [-1.,  0., -1.],
       [-1., -1.,  0.]])